version: "3"
services:
  app:
    build: .
    hostname: dolibarr
    image: dolibarr-app
    restart: unless-stopped
  
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    ports:
      - 3307:3306

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - default
    depends_on:
      - app
    restart: always

    ports:
      - 8008:80

volumes:
  db: