version: "3"
services:
  app:
    image: dolibarr-app
    restart: no
    ports:
      - 8088:80
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    ports:
      - 3307:3306