version: "3"
services:
  app:
    hostname: dolibarr
    image: dolibarr-app
    restart: unless-stopped
    
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
      MYSQL_USER: user
      MYSQL_PASSWORD: user

    ports:
      - 3306:3306

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr.rule=Host(`gestion.kalamar.xyz`,)
      - traefik.http.routers.dolibarr.tls=true
      - traefik.http.routers.dolibarr.tls.certresolver=le
    networks:
      - default
      - traefik-proxy
    depends_on:
      - app
    restart: always

volumes:
  db:

networks:
  traefik-proxy:
    external: true