version: "3"
services:
  app:
    hostname: dolibarr
    image: dolibarr-app
    restart: unless-stopped
    
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    labels:
      - traefik.enable=true
      - traefik.http.routers.dolibarr.rule=Host(`gestion.kalamar.xyz`,)
      - traefik.http.routers.dolibarr.tls=true
      - traefik.http.routers.dolibarr.tls.certresolver=le
    networks:
      - default
      - traefik-proxy
    depends_on:
      - app
    restart: always

networks:
  traefik-proxy:
    external: true